# local Data
title: entenhausen
baseurl: "/entenhausen" # the subpath of your site, e.g. /blog/
description: what's happening?
timezone: Europe/Berlin
emblem:
color: "#F23E36"

# Central data
url: "http://meetthepeople.in" # the base hostname & protocol for your site
twitter_username: meetthepeople_in
github_username:  meetthepeople

# central css
asset_path: "/assets" # "http://127.0.0.1:5000/assets" # move to baseurl/assets in production
mtp_css: "/css/main.css"

# Build settings
markdown: kramdown
permalink: :title
